language: python
services:
  - postgresql
python:
  - "3.6"
env:
  global:
  - TRAVIS_BUILD=true

cache:
  - $HOME/.cache/pip

before_install: 
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - pip install coveralls --ignore-installed

before_script:
  - psql -c "CREATE DATABASE updown;" -U postgres

script:
  - python manage.py test --noinput
  - coverage run --omit='*virtualenv*' manage.py test

after_success: coveralls
