language: python
services:
  - postgresql
python:
  - "3.6"
env:
  global:
  - TRAVIS_BUILD=true

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE updown;" -U postgres

script:
  - cd bucketlist
  - python manage.py test --noinput
  - coverage run --omit='*virtualenv*' manage.py test --noinput
after_success: coveralls
