# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:22
from __future__ import unicode_literals

import api.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('datemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.DateMixin')),
                ('file_id', models.CharField(default=api.utils.generate_uid, max_length=50)),
                ('_file', models.FileField(upload_to=api.utils.get_file_upload_path)),
            ],
            bases=('api.datemixin',),
        ),
    ]
