# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 10:05
from __future__ import unicode_literals

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170901_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='datemixin',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='datemixin',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default=api.utils.generate_uid, max_length=20),
        ),
    ]
